const countryZoneMap = {
  "Afghanistan": 10,
  "Albania": 7,
  "Algeria": 10,
  "American Samoa": 10,
  "Andorra": 7,
  "Angola": 10,
  "Anguilla": 10,
  "Antigua and Barbuda": 10,
  "Argentina": 9,
  "Armenia": 10,
  "Aruba": 10,
  "Australia": 6,
  "Austria": 7,
  "Azerbaijan": 10,
  "Bahamas": 10,
  "Bahrain": 4,
  "Bangladesh": 4,
  "Barbados": 10,
  "Belarus": 10,
  "Belgium": 7,
  "Belize": 10,
  "Benin": 10,
  "Bermuda": 10,
  "Bhutan": 10,
  "Bolivia": 9,
  "Bosnia and Herzegovina": 7,
  "Botswana": 10,
  "Brazil": 9,
  "Brunei": 5,
  "Bulgaria": 7,
  "Burkina Faso": 10,
  "Burundi": 10,
  "Cambodia": 5,
  "Cameroon": 8,
  "Canada": 7,
  "Cape Verde": 10,
  "Cayman Islands": 10,
  "Central African Republic": 10,
  "Chad": 10,
  "Chile": 9,
  "China": 3,
  "Colombia": 9,
  "Comoros": 10,
  "Congo": 10,
  "Costa Rica": 10,
  "Croatia": 7,
  "Cuba": 10,
  "Cyprus": 7,
  "Czech Republic": 7,
  "Denmark": 7,
  "Djibouti": 10,
  "Dominica": 10,
  "Dominican Republic": 10,

  "Ecuador": 9,
  "Egypt": 10,
  "El Salvador": 10,
  "Eritrea": 10,
  "Estonia": 7,
  "Eswatini": 10,
  "Ethiopia": 10,

  "Fiji": 10,
  "Finland": 7,
  "France": 7,
  "French Guiana": 9,

  "Gabon": 10,
  "Gambia": 10,
  "Georgia": 10,
  "Germany": 7,
  "Ghana": 10,
  "Gibraltar": 7,
  "Greece": 7,
  "Greenland": 10,
  "Grenada": 10,
  "Guadeloupe": 9,
  "Guam": 10,
  "Guatemala": 10,
  "Guinea": 10,
  "Guinea-Bissau": 10,
  "Guyana": 9,

  "Haiti": 10,
  "Honduras": 10,
  "Hong Kong": 2,
  "Hungary": 7,

  "Iceland": 10,
  "India": 1,
  "Indonesia": 5,
  "Iran": 10,
  "Iraq": 10,
  "Ireland": 7,
  "Israel": 7,
  "Italy": 7,

  "Jamaica": 10,
  "Japan": 5,
  "Jordan": 4,

  "Kazakhstan": 10,
  "Kenya": 10,
  "Kiribati": 10,
  "Kuwait": 4,
  "Kyrgyzstan": 10,

  "Laos": 5,
  "Latvia": 7,
  "Lebanon": 10,
  "Lesotho": 10,
  "Liberia": 10,
  "Libya": 10,
  "Liechtenstein": 7,
  "Lithuania": 7,
  "Luxembourg": 7,

  "Macau": 5,
  "Madagascar": 10,
  "Malawi": 10,
  "Malaysia": 2,
  "Maldives": 1,
  "Mali": 10,
  "Malta": 7,
  "Martinique": 9,
  "Mauritania": 10,
  "Mauritius": 10,
  "Mexico": 8,
  "Moldova": 10,
  "Monaco": 7,
  "Mongolia": 10,
  "Montenegro": 7,
  "Montserrat": 10,
  "Morocco": 10,
  "Mozambique": 10,
  "Myanmar": 5,

  "Namibia": 10,
  "Nauru": 10,
  "Nepal": 7,
  "Netherlands": 7,
  "New Caledonia": 10,
  "New Zealand": 6,
  "Nicaragua": 10,
  "Niger": 10,
  "Nigeria": 10,
  "North Macedonia": 7,
  "Norway": 7,

  "Oman": 4,

  "Pakistan": 4,
  "Palau": 10,
  "Panama": 10,
  "Papua New Guinea": 6,
  "Paraguay": 9,
  "Peru": 9,
  "Philippines": 5,
  "Poland": 7,
  "Portugal": 7,
  "Puerto Rico": 10,

  "Qatar": 4,

  "Reunion": 10,
  "Romania": 7,
  "Russia": 10,
  "Rwanda": 10,

  "Saint Helena": 10,
  "Samoa": 10,
  "San Marino": 7,
  "Saudi Arabia": 4,
  "Senegal": 10,
  "Serbia": 7,
  "Seychelles": 10,
  "Sierra Leone": 10,
  "Singapore": 2,
  "Slovakia": 7,
  "Slovenia": 7,
  "Solomon Islands": 10,
  "Somalia": 10,
  "South Africa": 9,
  "South Sudan": 10,
  "Spain": 7,
  "Sri Lanka": 1,
  "Sudan": 10,
  "Suriname": 9,
  "Sweden": 7,
  "Switzerland": 7,
  "Syria": 10,

  "Taiwan": 5,
  "Tajikistan": 10,
  "Tanzania": 10,
  "Thailand": 2,
  "Togo": 10,
  "Tonga": 10,
  "Trinidad and Tobago": 10,
  "Tunisia": 7,
  "Turkey": 7,

  "Uganda": 10,
  "Ukraine": 10,
  "United Arab Emirates": 1,
  "United Kingdom": 7,
  "United States": 9,
  "Uruguay": 9,
  "Uzbekistan": 10,

  "Vanuatu": 10,
  "Vatican City": 7,
  "Venezuela": 9,
  "Vietnam": 5,
  "Virgin Islands British": 10,

  "Yemen": 10,
  "Zambia": 10,
  "Zimbabwe": 10
};
